Repository learningequality/ricecooker, pull requests merged in 2024-03, with the labels that each got.

#476 Use blacklisted urls in the static assets
  ricecooker/utils/downloader.py
Labels: tech debt

#477 Download css background images
  ricecooker/utils/downloader.py
Labels: TAG: new feature

#479 Add action to send Slack notification about comments on issues
  .github/workflows/notify_team_new_comment.yml
Labels: needs review
